services:
  
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bookworm
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"